services:
  twineo:
    image: twineo:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CLIENTID=kimne78kx3ncx6brgo4mv6wki5h1ko
      - USERAGENT=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
    restart: unless-stopped
